name: release

# This workflow will run on master branch and on any pull requests targeting master
on:
  push:
    tags: ["v*"]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Build
        run: make releases

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/*
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
